# Generated by Django 2.0 on 2018-01-03 19:17

from django.db import migrations, models
import misc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('logo', models.ImageField(upload_to=misc.models.SlugifyUploadTo('partners', ['name']))),
                ('is_public', models.BooleanField()),
            ],
        ),
    ]
