# Generated by Django 2.0 on 2018-01-03 19:17

from django.db import migrations, models
import django.db.models.deletion
import misc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('photos', 'Photos'), ('article', 'Article'), ('other', 'Other')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('is_ready', models.BooleanField(default=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('website', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to=misc.models.SlugifyUploadTo('speakers', ['first_name', 'last_name']))),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('logo', models.ImageField(upload_to='sponsors')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('slides_file', models.FileField(blank=True, max_length=500, upload_to=misc.models.SlugifyUploadTo('slides', ['meetup', 'title']))),
                ('slides_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('language', models.CharField(choices=[('pl', 'Polish'), ('en', 'English')], default='pl', max_length=2)),
                ('meetup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='meetups.Meetup')),
                ('speakers', models.ManyToManyField(related_name='talks', to='meetups.Speaker')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TalkProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.Talk')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='meetup',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsored_meetups', to='meetups.Sponsor'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='meetups.Venue'),
        ),
        migrations.AddField(
            model_name='externallink',
            name='meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='meetups.Meetup'),
        ),
    ]
